bot_setup:
  periodic_time_frame: null
  send_periodic_message_during_events: false
gamedata:
  competition: {}
  events: {}
  guild: []
  players: []
startup:
  bot_token: TODO
  periodic_channel_id: 0
