startup:
  bot_token: "MTExNzA3MDIxMzkwNTY0OTcxNw.G1ghhu.pmA_1l4cUZrag2s6Xc8nK_U4vkf3mHnWu-lWlE"
  periodic_channel_id: 1117071205745295481

bot_setup:
  send_periodic_message_during_events: false
  periodic_time_frame: null

gamedata:
  guild:
    id: 75
    label: "GMC"
  competition: [] # Do not touch!
  players: []     # Do not touch!
  events: []      # Do not touch!